# TCL File Generated by Component Editor 18.1
# Wed May 22 14:07:36 CEST 2024
# DO NOT MODIFY


# 
# altera_temp_sense_ctrl "Altera Temperature Sensor Controller (Arria V)" v1.0
# Yifeng Wang 2024.05.22.14:07:36
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module altera_temp_sense_ctrl
# 
set_module_property DESCRIPTION ""
set_module_property NAME altera_temp_sense_ctrl
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Mu3e Control Plane/Modules"
set_module_property AUTHOR "Yifeng Wang"
set_module_property DISPLAY_NAME "Altera Temperature Sensor Controller (Arria V)"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL altera_temp_sense_ctrl
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_temp_sense_ctrl.vhd VHDL PATH altera_temp_sense_ctrl.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter CLK_FREQ NATURAL 40000000
set_parameter_property CLK_FREQ DEFAULT_VALUE 40000000
set_parameter_property CLK_FREQ DISPLAY_NAME CLK_FREQ
set_parameter_property CLK_FREQ TYPE NATURAL
set_parameter_property CLK_FREQ UNITS None
set_parameter_property CLK_FREQ ALLOWED_RANGES 0:2147483647
set_parameter_property CLK_FREQ HDL_PARAMETER true
add_parameter DEBUG NATURAL 0
set_parameter_property DEBUG DEFAULT_VALUE 0
set_parameter_property DEBUG DISPLAY_NAME DEBUG
set_parameter_property DEBUG TYPE NATURAL
set_parameter_property DEBUG ENABLED false
set_parameter_property DEBUG UNITS None
set_parameter_property DEBUG ALLOWED_RANGES 0:2147483647
set_parameter_property DEBUG HDL_PARAMETER true


# 
# display items
# 


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock system_clock
set_interface_property csr associatedReset system_reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr maximumPendingWriteTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr avs_csr_read read Input 1
add_interface_port csr avs_csr_write write Input 1
add_interface_port csr avs_csr_readdata readdata Output 32
add_interface_port csr avs_csr_writedata writedata Input 32
add_interface_port csr avs_csr_waitrequest waitrequest Output 1
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point system_clock
# 
add_interface system_clock clock end
set_interface_property system_clock clockRate 0
set_interface_property system_clock ENABLED true
set_interface_property system_clock EXPORT_OF ""
set_interface_property system_clock PORT_NAME_MAP ""
set_interface_property system_clock CMSIS_SVD_VARIABLES ""
set_interface_property system_clock SVD_ADDRESS_GROUP ""

add_interface_port system_clock i_clk clk Input 1


# 
# connection point system_reset
# 
add_interface system_reset reset end
set_interface_property system_reset associatedClock system_clock
set_interface_property system_reset synchronousEdges DEASSERT
set_interface_property system_reset ENABLED true
set_interface_property system_reset EXPORT_OF ""
set_interface_property system_reset PORT_NAME_MAP ""
set_interface_property system_reset CMSIS_SVD_VARIABLES ""
set_interface_property system_reset SVD_ADDRESS_GROUP ""

add_interface_port system_reset i_rst reset Input 1


# 
# connection point ce
# 
add_interface ce conduit end
set_interface_property ce associatedClock ""
set_interface_property ce associatedReset ""
set_interface_property ce ENABLED true
set_interface_property ce EXPORT_OF ""
set_interface_property ce PORT_NAME_MAP ""
set_interface_property ce CMSIS_SVD_VARIABLES ""
set_interface_property ce SVD_ADDRESS_GROUP ""

add_interface_port ce ce ce Output 1


# 
# connection point clr
# 
add_interface clr reset start
set_interface_property clr associatedClock system_clock
set_interface_property clr associatedDirectReset ""
set_interface_property clr associatedResetSinks ""
set_interface_property clr synchronousEdges DEASSERT
set_interface_property clr ENABLED true
set_interface_property clr EXPORT_OF ""
set_interface_property clr PORT_NAME_MAP ""
set_interface_property clr CMSIS_SVD_VARIABLES ""
set_interface_property clr SVD_ADDRESS_GROUP ""

add_interface_port clr clr reset Output 1


# 
# connection point tsdcaldone
# 
add_interface tsdcaldone conduit end
set_interface_property tsdcaldone associatedClock ""
set_interface_property tsdcaldone associatedReset ""
set_interface_property tsdcaldone ENABLED true
set_interface_property tsdcaldone EXPORT_OF ""
set_interface_property tsdcaldone PORT_NAME_MAP ""
set_interface_property tsdcaldone CMSIS_SVD_VARIABLES ""
set_interface_property tsdcaldone SVD_ADDRESS_GROUP ""

add_interface_port tsdcaldone tsdcaldone tsdcaldone Input 1


# 
# connection point tsdcalo
# 
add_interface tsdcalo conduit end
set_interface_property tsdcalo associatedClock ""
set_interface_property tsdcalo associatedReset ""
set_interface_property tsdcalo ENABLED true
set_interface_property tsdcalo EXPORT_OF ""
set_interface_property tsdcalo PORT_NAME_MAP ""
set_interface_property tsdcalo CMSIS_SVD_VARIABLES ""
set_interface_property tsdcalo SVD_ADDRESS_GROUP ""

add_interface_port tsdcalo tsdcalo tsdcalo Input 8

